I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/hospital_two.rpy", line 88, in script call
    call explosion("center_label_1")
  File "game/lib/explosion.rpy", line 25, in script call
    call center_label
  File "game/scripts/hospital_two.rpy", line 88, in script call
    call explosion("center_label_1")
  File "game/lib/explosion.rpy", line 25, in script call
    call center_label
ScriptError: could not find label 'center_label'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/hospital_two.rpy", line 88, in script call
    call explosion("center_label_1")
  File "game/lib/explosion.rpy", line 25, in script call
    call center_label
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/scripts/hospital_two.rpy", line 88, in script call
    call explosion("center_label_1")
  File "game/lib/explosion.rpy", line 25, in script call
    call center_label
  File "D:\RenPy\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'center_label'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
PPT Test 1.0
Tue Nov 14 16:08:49 2023
